name: RevTree CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: |
          rufo -c lib/
          bundle exec rspec

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Build the gem
        run: make

      - name: Install the gem
        run: make install

      - name: Save gem as artifact
        uses: actions/upload-artifact@v4
        with:
          name: revtree-gem
          path: 'revtree-*.gem'

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download built gem
        uses: actions/download-artifact@v4
        with:
          name: revtree-gem

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install RubyGems
        run: gem install rubygems-update

      - name: Update RubyGems
        run: update_rubygems

      - name: Push gem to RubyGems
        run: |
          gem push revtree-*.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
