name: RevTree CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@52753b7da854d5c07df37391a986c76ab4615999
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: |
          rufo -c lib/
          bundle exec rspec

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@52753b7da854d5c07df37391a986c76ab4615999
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the gem
        run: make

      - name: Install the gem
        run: make install

      - name: Save gem as artifact
        uses: actions/upload-artifact@v4
        with:
          name: revtree-gem
          path: 'revtree-*.gem'

      - name: Install the gem
        run: yard doc

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./doc"

  deploy-doc:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download built gem
        uses: actions/download-artifact@v4
        with:
          name: revtree-gem

      - name: Set up Ruby
        uses: ruby/setup-ruby@52753b7da854d5c07df37391a986c76ab4615999
        with:
          ruby-version: '3.0'

      - name: Install RubyGems
        run: gem install rubygems-update

      - name: Update RubyGems
        run: update_rubygems

      - name: Push gem to RubyGems
        run: |
          gem push revtree-*.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
